### PR TITLE
feat(upgrade-pomerium): upgrade image from 0.25.0 to 0.27.1

### PR DESCRIPTION
**Pull request by alfonsofortunato**
upgrade pomerium to nonroot-v1.27.1

### CODE REVIEW

**Review by ralgozino — COMMENTED** [review]
Hi @alfonsofortunato!

Some questions:
- Are there no changes to the manifests? Have you checked?
- Any breaking changes or major changes that we shold note in the release notes introduced in the new versions?
- Have you tested this version and the upgrade from the previous one?

**Comment by alfonsofortunato** [comment]
> Hi @alfonsofortunato!
> 
> Some questions:
> 
> * Are there no changes to the manifests? Have you checked?
> * Any breaking changes or major changes that we should note in the release notes introduced in the new versions?
> * Have you tested this version and the upgrade from the previous one?

I didn't notice any difference with the manifest with newer version. There are breaking changes, should I list there? I've tested the version on a local kind cluster and checked whether the pod is running. I created 2 dummy secrets for:

1. COOKIE_SECRET
2. SHARED_SECRET

and the pod is running (seems properly). I didn't have the change to test it on a fury distro since I haven't install a local fury distro yet. Should I test it on fury?

**Comment by ralgozino** [comment]
> I didn't notice any difference with the manifest with newer version.

cool.

>There are breaking changes, should I list there?

No need to list them all here. Did you find anything relevant that may have impact in how we use Pomerium? Something that we should repeat in the release notes of this module or at least link to?

> I've tested the version on a local kind cluster and checked whether the pod is running. I created 2 dummy secrets for:
> 
> 1. COOKIE_SECRET
> 2. SHARED_SECRET
> 
> and the pod is running (seems properly). I didn't have the chance to test it on a fury distro since I haven't install a local fury distro yet. Should I test it on fury?


This is the minimum test, ideally we should test this and that all the integrations still work properly (integration with dex, gangplank, ingresses are still protected, grafana dashboard still show the metrics, etc.), so, yes, ideally you should test this in a Fury cluster, it can be [Fury on Kind or minikube](https://docs.kubernetesfury.com/docs/quickstart/fury-on-minikube) but install at least the complete auth module.

**Review by ralgozino — APPROVED** [review]
We have tested the upgrade together and everything worked.

**Pull request merged**
